# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Max\Labs\KSKR\CourseWork\program\ui\ansys_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnsysWindow(object):
    def setupUi(self, AnsysWindow):
        AnsysWindow.setObjectName("AnsysWindow")
        AnsysWindow.resize(600, 300)
        AnsysWindow.setMinimumSize(QtCore.QSize(600, 300))
        AnsysWindow.setStyleSheet("*{color:rgb(198, 226, 255);}\n"
"QDialog{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"}\n"
"#inputFrame,#buttonFrame{\n"
"    border:2px outset rgb(0, 191, 255);\n"
"    border-radius:10px;\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"}\n"
"QLabel{\n"
"    min-height:35px;\n"
"    border:none;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLineEdit{\n"
"    min-height:35px;\n"
"    padding:3px;\n"
"    border:1px solid rgb(0, 191, 255);\n"
"    border-radius: 10px;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QLineEdit:focus{border:2px solid #c6e2ff;}\n"
"QPushButton{\n"
"    min-height:35px;\n"
"    padding:3px;\n"
"    border:2px outset rgb(0, 191, 255);\n"
"    border-radius: 10px;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(255, 0, 223, 44), stop:1 rgba(0, 0, 255, 49));\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(255, 0, 223, 44), stop:1 rgba(0, 0, 255, 49));\n"
"}\n"
"QMessageBox {\n"
"    border:2px solid rgb(0, 191, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AnsysWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputFrame = QtWidgets.QFrame(AnsysWindow)
        self.inputFrame.setMinimumSize(QtCore.QSize(0, 200))
        self.inputFrame.setStyleSheet("")
        self.inputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputFrame.setObjectName("inputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.inputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.inputFrame)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.nodesPathEdit = QtWidgets.QLineEdit(self.inputFrame)
        self.nodesPathEdit.setObjectName("nodesPathEdit")
        self.gridLayout.addWidget(self.nodesPathEdit, 0, 1, 1, 1)
        self.browseNodesButton = QtWidgets.QPushButton(self.inputFrame)
        self.browseNodesButton.setObjectName("browseNodesButton")
        self.gridLayout.addWidget(self.browseNodesButton, 0, 2, 1, 1)
        self.label2 = QtWidgets.QLabel(self.inputFrame)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.elemsPathEdit = QtWidgets.QLineEdit(self.inputFrame)
        self.elemsPathEdit.setObjectName("elemsPathEdit")
        self.gridLayout.addWidget(self.elemsPathEdit, 1, 1, 1, 1)
        self.browseElemsButton = QtWidgets.QPushButton(self.inputFrame)
        self.browseElemsButton.setObjectName("browseElemsButton")
        self.gridLayout.addWidget(self.browseElemsButton, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.inputFrame)
        self.buttonFrame = QtWidgets.QFrame(AnsysWindow)
        self.buttonFrame.setMaximumSize(QtCore.QSize(16777215, 71))
        self.buttonFrame.setStyleSheet("")
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uploadButton = QtWidgets.QPushButton(self.buttonFrame)
        self.uploadButton.setMinimumSize(QtCore.QSize(0, 45))
        self.uploadButton.setMaximumSize(QtCore.QSize(400, 16777215))
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout_2.addWidget(self.uploadButton)
        self.verticalLayout.addWidget(self.buttonFrame)

        self.retranslateUi(AnsysWindow)
        QtCore.QMetaObject.connectSlotsByName(AnsysWindow)

    def retranslateUi(self, AnsysWindow):
        _translate = QtCore.QCoreApplication.translate
        AnsysWindow.setWindowTitle(_translate("AnsysWindow", "Загрузка сетки из Ansys"))
        self.label1.setText(_translate("AnsysWindow", "Файл с узлами:"))
        self.browseNodesButton.setText(_translate("AnsysWindow", "Выбрать"))
        self.label2.setText(_translate("AnsysWindow", "Файл с элементами:"))
        self.browseElemsButton.setText(_translate("AnsysWindow", "Выбрать"))
        self.uploadButton.setText(_translate("AnsysWindow", "Загрузить файлы"))
