# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Max\Labs\KSKR\CourseWork\program\ui\materials_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaterialsWindow(object):
    def setupUi(self, MaterialsWindow):
        MaterialsWindow.setObjectName("MaterialsWindow")
        MaterialsWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MaterialsWindow.resize(900, 470)
        MaterialsWindow.setMinimumSize(QtCore.QSize(900, 470))
        MaterialsWindow.setStyleSheet("*{color:rgb(198, 226, 255);}\n"
"QDialog{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"}\n"
"QListWidget\n"
"{\n"
"    padding:5px;\n"
"    border:2px outset rgb(0, 191, 255);\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: 2px solid rgb(0, 191, 255);\n"
"    background: rgba(0, 0, 0, 0);\n"
"    width: 10px;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical{    \n"
"    background-color: rgb(128, 0, 128);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{background-color: rgb(255, 0, 127);}\n"
"QScrollBar::handle:vertical:pressed {background-color: rgb(185, 0, 92);}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {height: 0px;}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {height: 0px;}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::downarrow:vertical{background:none;}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{background: none;}\n"
"QListView::item{height:50px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QListView::item:hover{background : rgb(72, 61, 139);}\n"
"QListView::item:selected{border:1px solid rgb(0, 191, 255);\n"
"background :rgb(72,61, 139);}\n"
"#inputFrame,#buttonFrame{\n"
"    border:2px outset rgb(0, 191, 255);\n"
"    border-radius:10px;\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"}\n"
"QLabel{\n"
"    border:none;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLineEdit{\n"
"    padding:3px;\n"
"    border:1px solid rgb(0, 191, 255);\n"
"    border-radius: 10px;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QLineEdit:focus{border:2px solid #c6e2ff;}\n"
"QPushButton{\n"
"    min-height:35px;\n"
"    padding:3px;\n"
"    border:2px outset rgb(0, 191, 255);\n"
"    border-radius: 10px;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(255, 0, 223, 44), stop:1 rgba(0, 0, 255, 49));\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.994, stop:0 rgba(255, 0, 223, 44), stop:1 rgba(0, 0, 255, 49));\n"
"}\n"
"QMessageBox {\n"
"    border:2px solid rgb(0, 191, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(MaterialsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.materialsList = QtWidgets.QListWidget(MaterialsWindow)
        self.materialsList.setObjectName("materialsList")
        self.verticalLayout.addWidget(self.materialsList)
        self.inputFrame = QtWidgets.QFrame(MaterialsWindow)
        self.inputFrame.setStyleSheet("")
        self.inputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputFrame.setObjectName("inputFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inputFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(self.inputFrame)
        self.label1.setMinimumSize(QtCore.QSize(0, 38))
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.nameEdit = QtWidgets.QLineEdit(self.inputFrame)
        self.nameEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout.addWidget(self.nameEdit)
        self.label2 = QtWidgets.QLabel(self.inputFrame)
        self.label2.setMinimumSize(QtCore.QSize(0, 38))
        self.label2.setObjectName("label2")
        self.horizontalLayout.addWidget(self.label2)
        self.poissonEdit = QtWidgets.QLineEdit(self.inputFrame)
        self.poissonEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.poissonEdit.setObjectName("poissonEdit")
        self.horizontalLayout.addWidget(self.poissonEdit)
        self.label3 = QtWidgets.QLabel(self.inputFrame)
        self.label3.setMinimumSize(QtCore.QSize(0, 38))
        self.label3.setObjectName("label3")
        self.horizontalLayout.addWidget(self.label3)
        self.youngEdit = QtWidgets.QLineEdit(self.inputFrame)
        self.youngEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.youngEdit.setObjectName("youngEdit")
        self.horizontalLayout.addWidget(self.youngEdit)
        self.verticalLayout.addWidget(self.inputFrame)
        self.buttonFrame = QtWidgets.QFrame(MaterialsWindow)
        self.buttonFrame.setStyleSheet("")
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveButton = QtWidgets.QPushButton(self.buttonFrame)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 45))
        self.saveButton.setMaximumSize(QtCore.QSize(400, 16777215))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.removeButton = QtWidgets.QPushButton(self.buttonFrame)
        self.removeButton.setMinimumSize(QtCore.QSize(0, 45))
        self.removeButton.setMaximumSize(QtCore.QSize(400, 16777215))
        self.removeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.closeButton = QtWidgets.QPushButton(self.buttonFrame)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 45))
        self.closeButton.setMaximumSize(QtCore.QSize(400, 16777215))
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.buttonFrame)

        self.retranslateUi(MaterialsWindow)
        QtCore.QMetaObject.connectSlotsByName(MaterialsWindow)

    def retranslateUi(self, MaterialsWindow):
        _translate = QtCore.QCoreApplication.translate
        MaterialsWindow.setWindowTitle(_translate("MaterialsWindow", "Материалы"))
        self.label1.setText(_translate("MaterialsWindow", "Материал :"))
        self.label2.setText(_translate("MaterialsWindow", "Коэффициент Пуассона:"))
        self.label3.setText(_translate("MaterialsWindow", "Модуль Юнга:"))
        self.saveButton.setText(_translate("MaterialsWindow", "Сохранить"))
        self.removeButton.setText(_translate("MaterialsWindow", "Удалить"))
        self.closeButton.setText(_translate("MaterialsWindow", "Завершить редактирование"))